### PR TITLE
Bugfix/lixin/multiprocessing

### PR DESCRIPTION
**Pull request by nw13slx**
Temporarily fix the multithread nesting bug in #89 by removing the set_L_alpha sanity check from the parallelization.

More to do: 
1. replace the concurrent package in predict.py with multiprocessing. 
2. integrate the multiprocessing with pathos and slurm. So it can handle multinode environment.

### CODE REVIEW

**Comment by YuuuuXie** [comment]
> Temporarily fix the multithread nesting bug in #89 by removing the set_L_alpha sanity check outside of the parallelization.
> 
> More to do:
> 
> 1. replace the concurrent package in predict.py with multiprocessing.
> 2. integrate the multiprocessing with pathos and slurm. So it can handle multinode environment.

(I have a branch for parallelization, maybe we can contribute to that branch for integration with pathos and slurm. )

**Comment by YuuuuXie** [comment]
Is the module `md.py` in use? @jonpvandermause , we also need to move out the "predict" functions
I see there's also `concurrent` used there @nw13slx

**Comment by nw13slx** [comment]
> Is the module `md.py` in use? @jonpvandermause , we also need to move out the "predict" functions
> I see there's also `concurrent` used there @nw13slx

Yes. Let's also remove those functions.

**Comment by nw13slx** [comment]
close #89

**Pull request merged**
